# Generated by Django 3.2.6 on 2021-08-23 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
                ('timestamp_modified', models.DateTimeField(auto_now=True, verbose_name='Time Modified')),
                ('title', models.CharField(default=None, max_length=100)),
                ('content', models.TextField(verbose_name='Content')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voted', models.BooleanField(default=False)),
                ('voted_choice', models.CharField(default=None, max_length=10, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pollPage.polls')),
            ],
        ),
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_str', models.CharField(default=None, max_length=10)),
                ('vote_count', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollPage.polls')),
            ],
        ),
    ]
