# Generated by Django 3.1.2 on 2021-08-21 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='PollUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voted', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollPage.polloptions')),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
                ('timestamp_modified', models.DateTimeField(auto_now=True, verbose_name='Time Modified')),
                ('content', models.TextField(verbose_name='Content')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='polloptions',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollPage.polls'),
        ),
    ]
