# Generated by Django 3.1.2 on 2021-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloptions',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
