# Generated by Django 3.1.2 on 2021-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollPage', '0002_polloptions_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
