# Generated by Django 3.1.2 on 2021-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollPage', '0003_polls_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloptions',
            name='time',
        ),
        migrations.AddField(
            model_name='polloptions',
            name='time_str',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
