# Generated by Django 3.1.2 on 2021-08-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollPage', '0004_auto_20210821_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollusers',
            old_name='poll_option',
            new_name='pollOption',
        ),
    ]
