# Generated by Django 3.1.2 on 2021-08-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollPage', '0005_auto_20210821_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollusers',
            name='pollOption',
        ),
        migrations.AddField(
            model_name='pollusers',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pollPage.polls'),
        ),
    ]
