# Generated by Django 3.1.2 on 2021-08-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollPage', '0006_auto_20210822_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollusers',
            name='voted_choice',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
