# Generated by Django 3.1.2 on 2021-08-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
